services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-delivery
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - delivery
networks:
  delivery: